#!/bin/bash
. .env
REPO="$1"
KEY="$2"
EC2IP="$3"

function print_usage() {
    echo "Usage: $0 <user/repo> <key> <ec2ip>"
}

function print_set_pat() {
    echo "Please set GitHub Personal Access Token:"
    echo "echo 'PAT=ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > .env"
}

function check_push_permission() {
    echo "Checking for push permission..."
    TEST_BRANCH="test_branch_$(xxd -l16 -ps /dev/urandom)"
    cd `mktemp -d`
    git init > /dev/null 2>&1
    echo 'test' > test
    git add . 
    git commit -m "test" > /dev/null 2>&1
    git checkout -b "$TEST_BRANCH" > /dev/null 2>&1
    git push "git@github.com:$REPO.git" "$TEST_BRANCH" > /dev/null 2>&1
    git push "git@github.com:$REPO.git" --delete "$TEST_BRANCH" > /dev/null 2>&1
}

if [ -z "$REPO" ]; then
    print_usage; exit 1
fi

if [ -z "$KEY" ]; then
    print_usage; exit 1
fi

if [ -z "$EC2IP" ]; then
    print_usage; exit 1
fi

if [ -z "$PAT" ]; then
    print_set_pat; exit 1
fi

if ! check_push_permission; then
    echo "You don't have write access to that GitHub Repository"; exit 1
fi


echo "yayeyo"